In [1]:
import tensorflow as tlf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1785913205.956124   21685 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
I0000 00:00:1785913212.911199   21685 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1785913220.706344   21685 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.

In [2]:
df = pd.read_csv('insurance_data.csv')
df.head()

   age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [4]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    df[['age', 'affordibility']], df.bought_insurance, test_size=0.2, random_state=42
)

In [6]:
X_train

    age  affordibility
17   58              1
22   40              1
11   28              1
13   29              0
15   55              1
1    25              0
4    46              1
5    56              1
2    47              1
16   25              0
23   45              1
3    52              0
26   23              1
24   50              1
18   19              0
27   46              1
20   21              1
7    60              0
10   18              1
14   49              1
19   18              1
6    55              0